server:
  port: 7090

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  application:
    name: transaction-model-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7071/.well-known/jwks.json"

# &serverTimezone=UTC
  datasource:
    url: jdbc:mysql://10.0.0.31:3306/olive?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password: Pis9uPi8&?
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:    
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
  # thymeleaf:
  #   prefix: file://@project.basedir@/res/templates/
  #   cache: fals  
      
logging:
  file:
    name: ./logs/transaction-model-server.log

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
